name: Feature request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea! Please provide enough detail for us to evaluate it.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives or workarounds?
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - UI/UX
        - Backend / data pipeline
        - ADS-B history
        - Other
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, or mockups.
